name: Build

on:
  push:
    branches: ["master"]
    paths:
      - "config/**"
  pull_request:
    branches: ["master"]
    paths:
      - "config/**"

  workflow_dispatch:
  schedule:
    - cron: "45 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    env:
      TQDM_MININTERVAL: 5
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git curl wget lsb-release sudo
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup rust cargo
        uses: cargo-bins/cargo-binstall@main
      - name: Setup bgpstream wandio repository
        run: >-
          curl -s https://pkg.caida.org/os/$(lsb_release -si|awk '{print tolower($0)}')/bootstrap.sh | bash
      - name: Install bgpstream library
        run: |
          apt-get update
          apt install -y bgpstream
      - name: Install bgpkit
        uses: taiki-e/install-action@v2
        with:
          tool: bgpkit-broker,bgpkit-parser
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
      - name: Install project
        run: pip install .
      - name: Generate ip lists
        run: bgpip-tools bgp generate -d -o ip-lists
      - name: Release ip lists
        run: .github/release-ip-lists.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
