name: Build

on:
  push:
    branches: ["master"]
    paths:
      - "config/**"
  pull_request:
    branches: ["master"]
    paths:
      - "config/**"

  workflow_dispatch:
  schedule:
    - cron: "45 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TQDM_MININTERVAL: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup rust cargo
        uses: cargo-bins/cargo-binstall@main
      - name: Setup bgpstream wandio repository
        run: >-
          curl -1sLf 'https://dl.cloudsmith.io/public/wand/libwandio/cfg/setup/bash.deb.sh' |
          sudo -E bash
      - name: Install bgpstream library
        run: sudo apt-get update && sudo apt install -y wget bgpstream
      - name: Install bgpkit
        uses: taiki-e/install-action@v2
        with:
          tool: bgpkit-broker,bgpkit-parser
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
      - name: Install project
        run: pip install .
      - name: Generate ip lists
        run: bgpip-tools bgp generate -d -o ip-lists
      - name: Release ip lists
        run: .github/release-ip-lists.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
