name: Build

on:
  push:
    branches: ["master"]
    paths:
      - "config/**"
  pull_request:
    branches: ["master"]
    paths:
      - "config/**"

  workflow_dispatch:
  schedule:
    - cron: "45 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3-bookworm
    env:
      TQDM_MININTERVAL: 5
      DISABLE_DOWNLOAD_PROGRESS: 1
      ASNINFO_VERSION: "0.2.1"
      BGPKIT_BROKER_VERSION: "0.7.6"
      BGPKIT_PARSER_VERSION: "0.10.6"
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git curl wget lsb-release sudo build-essential
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup rust cargo
        uses: cargo-bins/cargo-binstall@main
      - name: Setup bgpstream wandio repository
        run: >-
          curl -s https://pkg.caida.org/os/$(lsb_release -si|awk '{print tolower($0)}')/bootstrap.sh | bash
      - name: Install bgpstream library
        run: |
          apt-get update
          apt install -y bgpstream
      - name: Install bgpkit
        uses: taiki-e/install-action@v2
        with:
          tool: >-
            asninfo@${{ env.ASNINFO_VERSION }},
            bgpkit-broker@${{ env.BGPKIT_BROKER_VERSION }},
            bgpkit-parser@${{ env.BGPKIT_PARSER_VERSION }}
      - name: Install project
        run: pip install .
      - name: Check if config/stable changed
        id: config_stable
        run: |
          if git diff --diff-filter=d --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^config/stable/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Check if config/nightly changed
        id: config_nightly
        run: |
          if git diff --diff-filter=d --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^config/nightly/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Generate ip lists
        if: steps.config_stable.outputs.changed == 'true'
        run: bgpip-tools bgp generate -o ip-lists
      - name: Release ip lists
        if: steps.config_stable.outputs.changed == 'true'
        run: .github/release-ip-lists.sh ip-lists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate ip lists nightly
        if: steps.config_nightly.outputs.changed == 'true'
        run: bgpip-tools -c config/nightly bgp generate -o ip-lists-nightly
      - name: Release ip lists nightly
        if: steps.config_nightly.outputs.changed == 'true'
        run: .github/release-ip-lists.sh ip-lists-nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
